import { BiLogoPostgresql } from "react-icons/bi";
import { DiMongodb } from "react-icons/di";
import { FaAws, FaNodeJs } from "react-icons/fa";
import { FaBrave } from "react-icons/fa6";
import {
  SiDrizzle,
  SiExpress,
  SiGoogle,
  SiGooglegemini,
  SiJavascript,
  SiJsonwebtokens,
  SiMongodb,
  SiMongoose,
  SiNextdotjs,
  SiNextui,
  SiPrisma,
  SiRazorpay,
  SiReact,
  SiShadcnui,
  SiSocketdotio,
  SiStripe,
  SiTailwindcss,
  SiTypescript,
  SiUpstash,
  SiVercel,
} from "react-icons/si";

// ==================== FREELANCE PROJECTS ====================
export const FREELANCE_PROJECTS = [
  {
    title: "RankFlys - Education (Neet & Jee)",
    description:
      "Complete education platform for NEET & JEE aspirants with payment integration, course management, and AWS deployment.",
    tech: [
      { icon: FaNodeJs, name: "Node.js" },
      { icon: SiExpress, name: "Express" },
      { icon: BiLogoPostgresql, name: "PostgreSQL" },
      { icon: SiRazorpay, name: "Razorpay" },
      { icon: SiPrisma, name: "Prisma" },
      { icon: FaAws, name: "AWS" },
      { icon: SiNextui, name: "NextUI" },
      { icon: SiNextdotjs, name: "Next.js" },
      { icon: SiTypescript, name: "TypeScript" },
      { icon: SiTailwindcss, name: "Tailwind" },
      { icon: SiJsonwebtokens, name: "JWT" },
    ],
    link: "https://rankflys.vercel.app/",
    cover: "/project-images/rankflys.png",
    gradient: "from-indigo-500 via-purple-500 to-pink-500",
    tags: ["Full Stack", "Education", "Payment Gateway"],
  },
  {
    title: "SteelOnMobile - Brochure",
    description:
      "Modern brochure website for steel industry with responsive design, content management, and SEO optimization.",
    tech: [
      { icon: SiNextdotjs, name: "Next.js" },
      { icon: SiTypescript, name: "TypeScript" },
      { icon: SiTailwindcss, name: "Tailwind" },
      { icon: SiJsonwebtokens, name: "JWT" },
      { icon: SiShadcnui, name: "shadcn/ui" },
      { icon: DiMongodb, name: "MongoDB" },
      { icon: SiMongoose, name: "Mongoose" },
    ],
    link: "https://www.steelonmobile.com/",
    cover: "/project-images/steelonmobile.png",
    gradient: "from-blue-500 via-cyan-500 to-teal-500",
    tags: ["Frontend", "Brochure", "SEO"],
  },
];

// ==================== PERSONAL PROJECTS ====================
export const PERSONAL_PROJECTS = [
  {
    title: "Youth AF",
    subtitle: "Computer Science Learning Platform",
    description:
      "No fluff. No overcomplications. Just solid CS learning. Master programming, algorithms, data structures, and computer science fundamentals with practical, hands-on tutorials, notes, and resources for Classes 9-12.",
    tech: [
      { icon: SiNextdotjs, name: "Next.js" },
      { icon: SiReact, name: "React" },
      { icon: SiTypescript, name: "TypeScript" },
      { icon: SiTailwindcss, name: "Tailwind CSS" },
      { icon: SiDrizzle, name: "Drizzle ORM" },
      { icon: BiLogoPostgresql, name: "PostgreSQL" },
      { icon: SiVercel, name: "Vercel" },
      { icon: SiGoogle, name: "Google Adsense" },
      { icon: FaAws, name: "AWS S3" },
      { icon: SiUpstash, name: "Upstash Redis" },
    ],
    link: "https://youth-af.com",
    cover: "project-images/youth-af.png",
    gradient: "from-amber-500 to-yellow-500",
    tags: ["Education", "Computer Science", "Full Stack", "Next.js"],
    highlighted: true,
    stats: [
      { label: "Daily Visitors", value: "200+" },
      { label: "Lifetime Visitors", value: "50K+" },
      { label: "Total Requests", value: "2M+" },
    ],
  },
  {
    title: "Lunox.ai",
    subtitle: "Web Search + LLM Summarization",
    description:
      "AI-powered search engine that combines web search results with LLM summarization using Google Gemini and Brave Search API.",
    tech: [
      { icon: SiNextdotjs, name: "Next.js" },
      { icon: SiReact, name: "React" },
      { icon: SiTypescript, name: "TypeScript" },
      { icon: SiTailwindcss, name: "Tailwind" },
      { icon: "/inngest.png", name: "Inngest", type: "image" },
      { icon: SiGooglegemini, name: "Gemini AI" },
      { icon: FaBrave, name: "Brave Search" },
      { icon: SiDrizzle, name: "Drizzle ORM" },
      { icon: BiLogoPostgresql, name: "PostgreSQL" },
    ],
    link: "https://lunox.abhisheksingh.me",
    cover: "/project-images/lunox.png",
    gradient: "from-purple-500 to-pink-500",
    tags: ["AI", "Search Engine", "Full Stack"],
  },
  {
    title: "Pencil.io",
    subtitle: "Documents & Diagrams",
    description:
      "Collaborative document editor and diagram creator with real-time synchronization and Stripe payment integration.",
    tech: [
      { icon: SiNextdotjs, name: "Next.js" },
      { icon: SiReact, name: "React" },
      { icon: SiTypescript, name: "TypeScript" },
      { icon: SiJavascript, name: "JavaScript" },
      { icon: SiTailwindcss, name: "Tailwind" },
      { icon: SiJsonwebtokens, name: "JWT" },
      { icon: SiMongodb, name: "MongoDB" },
      { icon: SiStripe, name: "Stripe" },
    ],
    link: "https://pencil-io.abhisheksingh.me",
    cover: "/project-images/pencil-io.png",
    gradient: "from-indigo-500 to-purple-500",
    tags: ["Collaboration", "SaaS", "Payment"],
  },
  {
    title: "Event Ocean",
    subtitle: "Your Events, Our Platform",
    description:
      "Complete event management platform with ticket booking, payment processing, and event discovery features.",
    tech: [
      { icon: SiNextdotjs, name: "Next.js" },
      { icon: SiReact, name: "React" },
      { icon: SiTypescript, name: "TypeScript" },
      { icon: SiJavascript, name: "JavaScript" },
      { icon: SiTailwindcss, name: "Tailwind" },
      { icon: SiMongodb, name: "MongoDB" },
      { icon: SiStripe, name: "Stripe" },
    ],
    link: "https://event-ocean.abhisheksingh.me/",
    cover: "/project-images/event-ocean.png",
    gradient: "from-green-500 to-emerald-500",
    tags: ["Event Management", "Tickets", "SaaS"],
  },
  {
    title: "PromptHub",
    subtitle: "Discover & Share AI Prompts",
    description:
      "Community platform for discovering, sharing, and rating AI prompts for various use cases and models.",
    tech: [
      { icon: SiNextdotjs, name: "Next.js" },
      { icon: SiReact, name: "React" },
      { icon: SiJavascript, name: "JavaScript" },
      { icon: SiTailwindcss, name: "Tailwind" },
      { icon: SiJsonwebtokens, name: "JWT" },
      { icon: SiMongodb, name: "MongoDB" },
    ],
    link: "https://prompt-hub.abhisheksingh.me",
    cover: "/project-images/prompt-hub.png",
    gradient: "from-orange-500 to-red-500",
    tags: ["AI", "Community", "Prompts"],
  },
  {
    title: "Internhub",
    subtitle: "College Placement Cell",
    description:
      "Complete placement management system for colleges with student profiles, job postings, and application tracking.",
    tech: [
      { icon: SiNextdotjs, name: "Next.js" },
      { icon: SiReact, name: "React" },
      { icon: SiJavascript, name: "JavaScript" },
      { icon: SiTailwindcss, name: "Tailwind" },
      { icon: SiJsonwebtokens, name: "JWT" },
      { icon: SiMongodb, name: "MongoDB" },
      { icon: SiExpress, name: "Express" },
    ],
    link: "https://internhub.in",
    cover: "/project-images/internhub.png",
    gradient: "from-cyan-500 to-blue-500",
    tags: ["Placement", "College", "Management"],
  },
  {
    title: "Flixify",
    subtitle: "Watch Movies",
    description:
      "Movie streaming platform with extensive catalog, search functionality, and personalized recommendations.",
    tech: [
      { icon: SiNextdotjs, name: "Next.js" },
      { icon: SiReact, name: "React" },
      { icon: SiJavascript, name: "JavaScript" },
      { icon: SiTailwindcss, name: "Tailwind" },
      { icon: SiJsonwebtokens, name: "JWT" },
      { icon: SiMongodb, name: "MongoDB" },
    ],
    link: "https://flixify-ruby.vercel.app/",
    cover: "/project-images/flixify.png",
    gradient: "from-yellow-500 to-orange-500",
    tags: ["Streaming", "Entertainment", "Frontend"],
  },
  {
    title: "Livecode",
    subtitle: "Collaborative Coding",
    description:
      "Real-time collaborative code editor with syntax highlighting, live cursors, and instant synchronization.",
    tech: [
      { icon: SiNextdotjs, name: "Next.js" },
      { icon: SiReact, name: "React" },
      { icon: SiJavascript, name: "JavaScript" },
      { icon: SiTailwindcss, name: "Tailwind" },
      { icon: SiJsonwebtokens, name: "JWT" },
      { icon: SiMongodb, name: "MongoDB" },
      { icon: SiSocketdotio, name: "Socket.io" },
    ],
    link: "https://livecode-liart.vercel.app/",
    cover: "/project-images/livecode.png",
    gradient: "from-lime-500 to-green-500",
    tags: ["Real-time", "Collaboration", "IDE"],
  },
  {
    title: "Word Web",
    subtitle: "Stay Curious",
    description:
      "Educational platform for vocabulary building and word learning with interactive features and progress tracking.",
    tech: [
      { icon: SiNextdotjs, name: "Next.js" },
      { icon: SiReact, name: "React" },
      { icon: SiJavascript, name: "JavaScript" },
      { icon: SiTailwindcss, name: "Tailwind" },
      { icon: SiJsonwebtokens, name: "JWT" },
      { icon: SiMongodb, name: "MongoDB" },
      { icon: SiExpress, name: "Express" },
    ],
    link: "https://word-web-sigma.vercel.app/",
    cover: "/project-images/word-web.png",
    gradient: "from-pink-500 to-rose-500",
    tags: ["Education", "Full Stack", "Learning"],
  },
  {
    title: "Medicare",
    subtitle: "Online Doctor Appointments",
    description:
      "Healthcare platform for booking doctor appointments, managing patient records, and telemedicine consultations.",
    tech: [
      { icon: SiReact, name: "React" },
      { icon: SiJavascript, name: "JavaScript" },
      { icon: SiTailwindcss, name: "Tailwind" },
    ],
    link: "/",
    cover: "/project-images/medicare.png",
    gradient: "from-teal-500 to-cyan-500",
    tags: ["Healthcare", "Frontend", "Booking"],
  },
];
