import {
  IconBrandAws,
  IconBrandGoogle,
  IconBrandJavascript,
  IconBrandNextjs,
  IconBrandNodejs,
  IconBrandReact,
  IconBrandSocketIo,
  IconBrandTailwind,
  IconBrandTypescript,
  IconBrandVercel,
  IconCloud,
  IconDatabase,
  IconLock,
  IconShield,
} from "@tabler/icons-react";

// ==================== FREELANCE PROJECTS ====================
export const FREELANCE_PROJECTS = [
  {
    title: "RankFlys - Education (Neet & Jee)",
    description:
      "Complete education platform for NEET & JEE aspirants with payment integration, course management, and AWS deployment.",
    tech: [
      { icon: IconBrandNodejs, name: "Node.js" },
      { icon: IconBrandNodejs, name: "Express" },
      { icon: IconDatabase, name: "PostgreSQL" },
      { icon: IconShield, name: "Razorpay" },
      { icon: IconDatabase, name: "Prisma" },
      { icon: IconBrandAws, name: "AWS" },
      { icon: IconBrandReact, name: "NextUI" },
      { icon: IconBrandNextjs, name: "Next.js" },
      { icon: IconBrandTypescript, name: "TypeScript" },
      { icon: IconBrandTailwind, name: "Tailwind" },
      { icon: IconLock, name: "JWT" },
    ],
    link: "https://rankflys.vercel.app/",
    cover: "/project-images/rankflys.png",
    tags: ["Full Stack", "Education", "Payment Gateway"],
  },
  {
    title: "SteelOnMobile - Brochure",
    description:
      "Modern brochure website for steel industry with responsive design, content management, and SEO optimization.",
    tech: [
      { icon: IconBrandNextjs, name: "Next.js" },
      { icon: IconBrandTypescript, name: "TypeScript" },
      { icon: IconBrandTailwind, name: "Tailwind" },
      { icon: IconLock, name: "JWT" },
      { icon: IconBrandTailwind, name: "shadcn/ui" },
      { icon: IconDatabase, name: "MongoDB" },
      { icon: IconDatabase, name: "Mongoose" },
    ],
    link: "https://www.steelonmobile.com/",
    cover: "/project-images/steelonmobile.png",
    tags: ["Frontend", "Brochure", "SEO"],
  },
];

// ==================== PERSONAL PROJECTS ====================
export const PERSONAL_PROJECTS = [
  {
    title: "Youth AF",
    subtitle: "Computer Science Learning Platform",
    description:
      "No fluff. No overcomplications. Just solid CS learning. Master programming, algorithms, data structures, and computer science fundamentals with practical, hands-on tutorials, notes, and resources for Classes 9-12.",
    tech: [
      { icon: IconBrandNextjs, name: "Next.js" },
      { icon: IconBrandReact, name: "React" },
      { icon: IconBrandTypescript, name: "TypeScript" },
      { icon: IconBrandTailwind, name: "Tailwind CSS" },
      { icon: IconDatabase, name: "Drizzle ORM" },
      { icon: IconDatabase, name: "PostgreSQL" },
      { icon: IconBrandVercel, name: "Vercel" },
      { icon: IconBrandGoogle, name: "Google Adsense" },
      { icon: IconBrandAws, name: "AWS S3" },
      { icon: IconCloud, name: "Upstash Redis" },
    ],
    link: "https://youth-af.com",
    cover: "project-images/youth-af.png",
    tags: ["Education", "Computer Science", "Full Stack", "Next.js"],
    highlighted: true,
    stats: [
      { label: "Daily Visitors", value: "200+" },
      { label: "Lifetime Visitors", value: "50K+" },
      { label: "Total Requests", value: "2M+" },
    ],
  },
  {
    title: "Lunox.ai",
    subtitle: "Web Search + LLM Summarization",
    description:
      "AI-powered search engine that combines web search results with LLM summarization using Google Gemini and Brave Search API.",
    tech: [
      { icon: IconBrandNextjs, name: "Next.js" },
      { icon: IconBrandReact, name: "React" },
      { icon: IconBrandTypescript, name: "TypeScript" },
      { icon: IconBrandTailwind, name: "Tailwind" },
      { icon: "/inngest.png", name: "Inngest", type: "image" },
      { icon: IconCloud, name: "Gemini AI" },
      { icon: IconCloud, name: "Brave Search" },
      { icon: IconDatabase, name: "Drizzle ORM" },
      { icon: IconDatabase, name: "PostgreSQL" },
    ],
    link: "https://lunox.abhisheksingh.me",
    cover: "/project-images/lunox.png",
    tags: ["AI", "Search Engine", "Full Stack"],
  },
  {
    title: "Pencil.io",
    subtitle: "Documents & Diagrams",
    description:
      "Collaborative document editor and diagram creator with real-time synchronization and Stripe payment integration.",
    tech: [
      { icon: IconBrandNextjs, name: "Next.js" },
      { icon: IconBrandReact, name: "React" },
      { icon: IconBrandTypescript, name: "TypeScript" },
      { icon: IconBrandJavascript, name: "JavaScript" },
      { icon: IconBrandTailwind, name: "Tailwind" },
      { icon: IconLock, name: "JWT" },
      { icon: IconDatabase, name: "MongoDB" },
      { icon: IconShield, name: "Stripe" },
    ],
    link: "https://pencil-io.abhisheksingh.me",
    cover: "/project-images/pencil-io.png",
    tags: ["Collaboration", "SaaS", "Payment"],
  },
  {
    title: "Event Ocean",
    subtitle: "Your Events, Our Platform",
    description:
      "Complete event management platform with ticket booking, payment processing, and event discovery features.",
    tech: [
      { icon: IconBrandNextjs, name: "Next.js" },
      { icon: IconBrandReact, name: "React" },
      { icon: IconBrandTypescript, name: "TypeScript" },
      { icon: IconBrandJavascript, name: "JavaScript" },
      { icon: IconBrandTailwind, name: "Tailwind" },
      { icon: IconDatabase, name: "MongoDB" },
      { icon: IconShield, name: "Stripe" },
    ],
    link: "https://event-ocean.abhisheksingh.me/",
    cover: "/project-images/event-ocean.png",
    tags: ["Event Management", "Tickets", "SaaS"],
  },
  {
    title: "PromptHub",
    subtitle: "Discover & Share AI Prompts",
    description:
      "Community platform for discovering, sharing, and rating AI prompts for various use cases and models.",
    tech: [
      { icon: IconBrandNextjs, name: "Next.js" },
      { icon: IconBrandReact, name: "React" },
      { icon: IconBrandJavascript, name: "JavaScript" },
      { icon: IconBrandTailwind, name: "Tailwind" },
      { icon: IconLock, name: "JWT" },
      { icon: IconDatabase, name: "MongoDB" },
    ],
    link: "https://prompt-hub.abhisheksingh.me",
    cover: "/project-images/prompt-hub.png",
    tags: ["AI", "Community", "Prompts"],
  },
  {
    title: "Internhub",
    subtitle: "College Placement Cell",
    description:
      "Complete placement management system for colleges with student profiles, job postings, and application tracking.",
    tech: [
      { icon: IconBrandNextjs, name: "Next.js" },
      { icon: IconBrandReact, name: "React" },
      { icon: IconBrandJavascript, name: "JavaScript" },
      { icon: IconBrandTailwind, name: "Tailwind" },
      { icon: IconLock, name: "JWT" },
      { icon: IconDatabase, name: "MongoDB" },
      { icon: IconBrandNodejs, name: "Express" },
    ],
    link: "https://internhub.in",
    cover: "/project-images/internhub.png",
    tags: ["Placement", "College", "Management"],
  },
  {
    title: "Flixify",
    subtitle: "Watch Movies",
    description:
      "Movie streaming platform with extensive catalog, search functionality, and personalized recommendations.",
    tech: [
      { icon: IconBrandNextjs, name: "Next.js" },
      { icon: IconBrandReact, name: "React" },
      { icon: IconBrandJavascript, name: "JavaScript" },
      { icon: IconBrandTailwind, name: "Tailwind" },
      { icon: IconLock, name: "JWT" },
      { icon: IconDatabase, name: "MongoDB" },
    ],
    link: "https://flixify-ruby.vercel.app/",
    cover: "/project-images/flixify.png",
    tags: ["Streaming", "Entertainment", "Frontend"],
  },
  {
    title: "Livecode",
    subtitle: "Collaborative Coding",
    description:
      "Real-time collaborative code editor with syntax highlighting, live cursors, and instant synchronization.",
    tech: [
      { icon: IconBrandNextjs, name: "Next.js" },
      { icon: IconBrandReact, name: "React" },
      { icon: IconBrandJavascript, name: "JavaScript" },
      { icon: IconBrandTailwind, name: "Tailwind" },
      { icon: IconLock, name: "JWT" },
      { icon: IconDatabase, name: "MongoDB" },
      { icon: IconBrandSocketIo, name: "Socket.io" },
    ],
    link: "https://livecode-liart.vercel.app/",
    cover: "/project-images/livecode.png",
    tags: ["Real-time", "Collaboration", "IDE"],
  },
  {
    title: "Word Web",
    subtitle: "Stay Curious",
    description:
      "Educational platform for vocabulary building and word learning with interactive features and progress tracking.",
    tech: [
      { icon: IconBrandNextjs, name: "Next.js" },
      { icon: IconBrandReact, name: "React" },
      { icon: IconBrandJavascript, name: "JavaScript" },
      { icon: IconBrandTailwind, name: "Tailwind" },
      { icon: IconLock, name: "JWT" },
      { icon: IconDatabase, name: "MongoDB" },
      { icon: IconBrandNodejs, name: "Express" },
    ],
    link: "https://word-web-sigma.vercel.app/",
    cover: "/project-images/word-web.png",
    tags: ["Education", "Full Stack", "Learning"],
  },
  {
    title: "Medicare",
    subtitle: "Online Doctor Appointments",
    description:
      "Healthcare platform for booking doctor appointments, managing patient records, and telemedicine consultations.",
    tech: [
      { icon: IconBrandReact, name: "React" },
      { icon: IconBrandJavascript, name: "JavaScript" },
      { icon: IconBrandTailwind, name: "Tailwind" },
    ],
    link: "/",
    cover: "/project-images/medicare.png",
    tags: ["Healthcare", "Frontend", "Booking"],
  },
];
