import {
  IconBrandAws,
  IconBrandGoogle,
  IconBrandGoogleAnalytics,
  IconBrandJavascript,
  IconBrandNextjs,
  IconBrandNodejs,
  IconBrandReact,
  IconBrandTailwind,
  IconBrandTypescript,
  IconCloud,
  IconDatabase,
  IconLock,
  IconPlugConnected,
  IconShield,
  IconTerminal,
  IconTrain,
} from "@tabler/icons-react";

// ==================== FREELANCE PROJECTS ====================
export const FREELANCE_PROJECTS = [
  {
    title: "RankFlys - Education (Neet & Jee)",
    description:
      "Complete education platform for NEET & JEE aspirants with payment integration, course management, and AWS deployment.",
    tech: [
      { icon: IconBrandNodejs, name: "Node.js" },
      { icon: IconBrandNodejs, name: "Express" },
      { icon: IconDatabase, name: "PostgreSQL" },
      { icon: IconShield, name: "Razorpay" },
      { icon: IconDatabase, name: "Prisma" },
      { icon: IconBrandAws, name: "AWS" },
      { icon: IconBrandReact, name: "NextUI" },
      { icon: IconBrandNextjs, name: "Next.js" },
      { icon: IconBrandTypescript, name: "TypeScript" },
      { icon: IconBrandTailwind, name: "Tailwind" },
      { icon: IconLock, name: "JWT" },
    ],
    link: "https://rankflys.vercel.app/",
    cover: "/project-images/rankflys.png",
    tags: ["Full Stack", "Education", "Payment Gateway"],
  },
  {
    title: "SteelOnMobile - Brochure",
    description:
      "Modern brochure website for steel industry with responsive design, content management, and SEO optimization.",
    tech: [
      { icon: IconBrandNextjs, name: "Next.js" },
      { icon: IconBrandTypescript, name: "TypeScript" },
      { icon: IconBrandTailwind, name: "Tailwind" },
      { icon: IconLock, name: "JWT" },
      { icon: IconBrandTailwind, name: "shadcn/ui" },
      { icon: IconDatabase, name: "MongoDB" },
      { icon: IconDatabase, name: "Mongoose" },
    ],
    link: "https://www.steelonmobile.com/",
    cover: "/project-images/steelonmobile.png",
    tags: ["Frontend", "Brochure", "SEO"],
  },
];

// ==================== PERSONAL PROJECTS ====================
export const PERSONAL_PROJECTS = [
  {
    title: "Youth AF",
    subtitle: "Computer Science Learning Platform · Live Jan 2026",
    description:
      "Designed and built the entire platform solo (frontend, backend, and infrastructure) with end-to-end type safety via Eden treaty contracts. Built the monetization layer with Razorpay course purchases, signature-verified webhooks, server-side access gating and S3-delivered PDFs/videos (1,360+ purchases, INR 59,000+ revenue). Scaled to 148K+ visitors, 1.22M+ page views and 231K+ sessions with 10% bounce rate and 25+ min avg session using SSG/ISR and TanStack Query with SSR hydration. Migrated from Vercel/Neon to Railway with server and DB on the same private network to cut DB latency to near-localhost. Admin operations suite on Better Auth with API-layer permission enforcement.",
    tech: [
      { icon: IconBrandNextjs, name: "Next.js" },
      { icon: IconBrandTypescript, name: "TypeScript" },
      { icon: IconBrandNodejs, name: "Elysia" },
      { icon: IconBrandNodejs, name: "Bun" },
      { icon: IconPlugConnected, name: "Drizzle ORM" },
      { icon: IconDatabase, name: "PostgreSQL" },
      { icon: IconDatabase, name: "Redis" },
      { icon: IconTrain, name: "Railway" },
      { icon: IconBrandAws, name: "AWS S3" },
      { icon: IconShield, name: "Razorpay" },
      { icon: IconBrandTailwind, name: "Tailwind CSS" },
      { icon: IconBrandGoogle, name: "Google Adsense" },
      { icon: IconBrandGoogleAnalytics, name: "PostHog" },
    ],
    link: "https://youth-af.com",
    cover: "project-images/youth-af.png",
    tags: ["Education", "Full Stack", "Elysia", "Drizzle ORM"],
    highlighted: true,
    stats: [
      { label: "Visitors", value: "148K+" },
      { label: "Page Views", value: "1.22M+" },
      { label: "Registered Users", value: "11,000+" },
      { label: "Revenue", value: "INR 59K+" },
    ],
  },
  {
    title: "CeroCode",
    subtitle: "Terminal-based AI Coding Agent · Aug 2026 · npm",
    description:
      "Terminal-based AI coding agent in the same category as Claude Code and OpenCode: a full harness handling agent orchestration, tool execution, and safety rather than a thin wrapper around a model API, published to npm. Core agent loop with streaming tool-call execution, PLAN/BUILD mode gating across 7 built-in tools (file read/write, bash, grep, glob, and more), and JSONB-persisted sessions so conversations survive restarts. Safety layer with sandboxed path resolution against symlink escapes, bash command allowlist, automatic detection of sensitive files like lockfiles and .env, default-deny approvals with session-scoped trust, and layered timeouts with bounded tool output.",
    tech: [
      { icon: IconBrandTypescript, name: "TypeScript" },
      { icon: IconBrandNodejs, name: "Bun" },
      { icon: IconTerminal, name: "React (OpenTUI)" },
      { icon: IconCloud, name: "Hono" },
      { icon: IconCloud, name: "AI SDK" },
      { icon: IconPlugConnected, name: "Drizzle ORM" },
      { icon: IconDatabase, name: "PostgreSQL" },
      { icon: IconBrandNodejs, name: "Node.js" },
    ],
    link: "https://cerocode.heyabhishek.in",
    cover: "/project-images/cero.png",
    tags: ["AI", "CLI", "Agent Harness", "OpenTUI"],
  },
  {
    title: "Event Ocean",
    subtitle: "Your Events, Our Platform",
    description:
      "Complete event management platform with ticket booking, payment processing, and event discovery features.",
    tech: [
      { icon: IconBrandNextjs, name: "Next.js" },
      { icon: IconBrandReact, name: "React" },
      { icon: IconBrandTypescript, name: "TypeScript" },
      { icon: IconBrandJavascript, name: "JavaScript" },
      { icon: IconBrandTailwind, name: "Tailwind" },
      { icon: IconDatabase, name: "MongoDB" },
      { icon: IconShield, name: "Stripe" },
    ],
    link: "https://event-ocean.heyabhishek.in/",
    cover: "/project-images/event-ocean.png",
    tags: ["Event Management", "Tickets", "SaaS"],
  },
  {
    title: "PromptHub",
    subtitle: "Discover & Share AI Prompts",
    description:
      "Community platform for discovering, sharing, and rating AI prompts for various use cases and models.",
    tech: [
      { icon: IconBrandNextjs, name: "Next.js" },
      { icon: IconBrandReact, name: "React" },
      { icon: IconBrandJavascript, name: "JavaScript" },
      { icon: IconBrandTailwind, name: "Tailwind" },
      { icon: IconLock, name: "JWT" },
      { icon: IconDatabase, name: "MongoDB" },
    ],
    link: "https://prompt-hub.heyabhishek.in",
    cover: "/project-images/prompt-hub.png",
    tags: ["AI", "Community", "Prompts"],
  },
  {
    title: "Pencil.io",
    subtitle: "Documents & Diagrams",
    description:
      "Collaborative document editor and diagram creator with real-time synchronization and Stripe payment integration.",
    tech: [
      { icon: IconBrandNextjs, name: "Next.js" },
      { icon: IconBrandReact, name: "React" },
      { icon: IconBrandTypescript, name: "TypeScript" },
      { icon: IconBrandJavascript, name: "JavaScript" },
      { icon: IconBrandTailwind, name: "Tailwind" },
      { icon: IconLock, name: "JWT" },
      { icon: IconDatabase, name: "MongoDB" },
      { icon: IconShield, name: "Stripe" },
    ],
    link: "https://pencil-io.heyabhishek.in",
    cover: "/project-images/pencil-io.png",
    tags: ["Collaboration", "SaaS", "Payment"],
  },
];
