// ==================== WORK EXPERIENCE ====================
export const WORK_EXPERIENCES = [
  {
    company: "SK Aggarwal and Co",
    role: "Full Stack Engineer",
    location: "Haryana, India",
    project: "Earnex Rewards - Loyalty Rewards Platform",
    highlights: [
      "Architected Earnex Rewards as a multi-tenant loyalty and analytics platform spanning 5 apps with shared packages for DB schemas, business logic, Zod validation, and email templates",
      "Engineered a 6-stage AI receipt verification pipeline with LLM OCR, authenticity checks, EXIF validation, arithmetic correctness, perceptual-hash dedupe, and automated decisioning",
      "Designed fraud and trust scoring using 5 signals across 4 risk tiers and 11 flag types with resolution workflows and full admin audit trails",
      "Implemented Shopify OAuth, webhook registration, and BullMQ-backed async sync for orders, customers, products, and line items",
      "Built a coin wallet and rewards ledger with 4-stage offer and coupon lifecycle, milestone tracking, and redemption analytics",
      "Activated lifecycle marketing with RFM segmentation across 6 behavioral segments, basket affinity analysis, churn indicators, and spend split insights",
    ],
    tech: [
      "Turborepo",
      "Next.js",
      "PostgreSQL",
      "Redis",
      "Node.js",
      "React Native",
      "Expo",
      "BullMQ",
      "Shopify",
      "AWS (EC2, S3)",
    ],
  },
  {
    company: "Nextfly Technologies Pvt. Ltd.",
    role: "Full Stack Developer",
    location: "Haryana, India",
    project: "Scraplo & MyDeer",
    highlights: [
      "Built Scraplo end-to-end as a logistics marketplace across 5 roles with RBAC and full flow from pickup scheduling to weighing and payout",
      "Implemented geolocation-based order assignment within a 5 km radius with real-time pickup tracking",
      "Integrated Google Maps coordinate polling, route rendering, and live ETA updates for customers",
      "Built a Razorpay-backed digital wallet covering earnings, withdrawals, reconciliation, and transaction history",
      "Automated payouts tied to order completion with audit-ready records",
    ],
    tech: [
      "Next.js",
      "React Native",
      "Node.js",
      "Express.js",
      "PostgreSQL",
      "Prisma",
      "Google Maps",
      "Razorpay",
    ],
  },
];
