// ==================== WORK EXPERIENCE ====================
export const WORK_EXPERIENCES = [
  {
    company: "SK Aggarwal and Co",
    role: "Full Stack Engineer",
    period: "September 2025 - Present",
    location: "Delhi, India",
    project: "Earnex Rewards - Loyalty Rewards Platform",
    highlights: [
      "Architected enterprise-grade monorepo using Turborepo with 5 interconnected applications",
      "Designed 6-layer receipt verification system with AI-powered fraud detection (ELA, EXIF validation, OCR)",
      "Built comprehensive admin dashboard and cross-platform mobile app using Expo React Native",
      "Implemented multi-layer security with device fingerprinting and automated risk scoring",
      "Integrated Google Gemini AI, AWS S3, Inngest workflows, and Better Auth",
    ],
    tech: [
      "Turborepo",
      "Next.js",
      "React Native",
      "Expo",
      "Drizzle ORM",
      "PostgreSQL",
      "AWS S3",
      "Gemini AI",
      "Inngest",
    ],
    gradient: "from-green-400 to-blue-500",
  },
  {
    company: "Nextfly Technologies Pvt. Ltd.",
    role: "Full Stack Developer",
    period: "August 2024 - August 2025",
    location: "Remote",
    project: "Scraplo & MyDeer",
    highlights: [
      "Engineered scrap marketplace serving 5 user types with region-based pricing architecture",
      "Implemented real-time GPS tracking with 5km radius geolocation-based order assignment",
      "Built bidirectional chat system using Server-Side Events (SSE) with tRPC for MyDeer platform",
      "Developed digital wallet system and integrated Razorpay payment gateway",
      "Created comprehensive admin dashboards with multi-stage approval workflows",
    ],
    tech: [
      "Next.js",
      "React Native",
      "Express.js",
      "PostgreSQL",
      "Prisma",
      "tRPC",
      "Socket.io",
      "Razorpay",
    ],
    gradient: "from-purple-400 to-pink-500",
  },
];
